version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: college_portal
      POSTGRES_USER: college_user
      POSTGRES_PASSWORD: college_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U college_user -d college_portal"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://college_user:college_pass@postgres:5432/college_portal
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET_KEY=dev-secret-key-change-in-production
      - JWT_REFRESH_SECRET_KEY=dev-refresh-secret-key-change-in-production
      - EMAIL_USERNAME=arundd2004@gmail.com
      - EMAIL_PASSWORD=jnlylfsewiuciljs
      - FRONTEND_URL=http://localhost:3000
      - ENVIRONMENT=development
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./backend:/app
      - backend_uploads:/app/uploads
    command: >
      sh -c "
        alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data:
  redis_data:
  backend_uploads: